config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = %w{ www admin}
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end

Rails.application.routes.draw do

  constraints SubdomainConstraint do
    get '/' => 'lecturer_home#index'
    
    devise_for :lecturers, :controllers => { :registrations => "registrations" }
    
    
    resources :courses do
      resources :materials
    end
    
  end

  root 'pages#index'  

  resources :universities#, only: [:new]

end

app/models/university.rb
class University < ActiveRecord::Base
	after_create :create_tenant

	validates :subdomain, exclusion: { in: %w(www admin us ca jp), message: "%{value} is reserved." }
	validates :subdomain, length: { in: 6..20 }
	validates :subdomain, uniqueness: true
	validates :name, :site, :logo, :portal, :subdomain, presence: true

	has_many :faculty

	private

	def create_tenant
		Apartment::Tenant.create(subdomain)
	end

end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
  before_action :set_university, only: [:show, :edit, :update, :destroy]

  # GET /universities
  # GET /universities.json
  def index
    @universities = University.all
  end

  # GET /universities/1
  # GET /universities/1.json
  def show
  end

  # GET /universities/new
  def new
    @university = University.new
  end

  # GET /universities/1/edit
  def edit
  end

  # POST /universities
  # POST /universities.json
  def create
    @university = University.new(university_params)

    respond_to do |format|
      if @university.save
        format.html { redirect_to @university, notice: 'University was successfully created.' }
        format.json { render :show, status: :created, location: @university }
      else
        format.html { render :new }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universities/1
  # PATCH/PUT /universities/1.json
  def update
    respond_to do |format|
      if @university.update(university_params)
        format.html { redirect_to @university, notice: 'University was successfully updated.' }
        format.json { render :show, status: :ok, location: @university }
      else
        format.html { render :edit }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universities/1
  # DELETE /universities/1.json
  def destroy
    @university.destroy
    respond_to do |format|
      format.html { redirect_to universities_url, notice: 'University was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_university
      @university = University.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def university_params
      params.require(:university).permit(:name, :site, :logo, :portal, :subdomain)
    end
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/views/universities/_form.html.erb
<%= form_for(@university) do |f| %>
  <% if @university.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@university.errors.count, "error") %> prohibited this university from being saved:</h2>

      <ul>
      <% @university.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, required:true, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :site %>
    <%= f.text_field :site, required:true, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :logo %>
    <%= f.text_field :logo, required:true, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "University Portal" %>
    <%= f.text_field :portal, required:true, class:"form-control" %>
  </div>
  <div class="form-group">
    <div class="input-group">
      <%= f.label :subdomain %>
      <%= f.text_field :subdomain, required:true, class:"form-control" %>
        <div class="input-group-addon">.studystudio.ng</div>
    </div>
  </div>  
  <div class="actions">
    <%= f.submit t('.sign_up', :default => "Sign up"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/universities/edit.html.erb
<h1>Editing University</h1>

<%= render 'form' %>

app/views/universities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Universities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Site</th>
      <th>Logo</th>
      <th>Portal</th>
      <th>Subdomain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @universities.each do |university| %>
      <tr>
        <td><%= university.name %></td>
        <td><%= university.site %></td>
        <td><%= university.logo %></td>
        <td><%= university.portal %></td>
        <td><%= university.subdomain %></td>
        <td><%= link_to 'Show', university %></td>
        <td><%= link_to 'Edit', edit_university_path(university) %></td>
        <td><%= link_to 'Destroy', university, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New University', new_university_path %>

app/views/universities/new.html.erb
<h1>Setup New University</h1>

<%= render 'form' %>

app/views/universities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @university.name %>
</p>

<p>
  <strong>Site:</strong>
  <%= @university.site %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @university.logo %>
</p>

<p>
  <strong>Portal:</strong>
  <%= @university.portal %>
</p>

<p>
  <strong>Subdomain:</strong>
  <%= @university.subdomain %>
</p>

<%= link_to 'Edit', edit_university_path(@university) %>